
import React, { useState } from 'react';
import { IELTS_STUDY_PLAN } from './constants';
import WeekTabs from './components/WeekTabs';
import DayCard from './components/DayCard';
import { WeeklyPlan } from './types';

const App: React.FC = () => {
  const [activeWeek, setActiveWeek] = useState(1);

  const selectedWeekPlan: WeeklyPlan | undefined = IELTS_STUDY_PLAN.find(
    (week) => week.week === activeWeek
  );

  return (
    <div className="min-h-screen bg-gray-900 text-gray-200 font-sans">
      <div className="container mx-auto p-4 md:p-8">
        <header className="text-center mb-8 md:mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-2">
            Lộ Trình Học IELTS Cấp Tốc
          </h1>
          <p className="text-lg text-cyan-400">Tháng 11 - Bắt đầu từ 03/11/2025</p>
        </header>

        <main>
          <WeekTabs
            weeks={[1, 2, 3, 4]}
            activeWeek={activeWeek}
            onSelectWeek={setActiveWeek}
          />

          {selectedWeekPlan && (
            <div className="mt-8">
              <div className="text-center mb-8 p-6 bg-gray-800/50 border border-gray-700 rounded-xl shadow-lg">
                <h2 className="text-3xl font-semibold text-white mb-2">{selectedWeekPlan.title}</h2>
                <p className="text-gray-400 max-w-3xl mx-auto">{selectedWeekPlan.description}</p>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {selectedWeekPlan.dailyPlans.map((plan) => (
                  <DayCard key={plan.day} plan={plan} />
                ))}
              </div>
            </div>
          )}
        </main>
        
        <footer className="text-center mt-12 text-gray-500 text-sm">
            <p>Generated by a world-class senior frontend React engineer.</p>
        </footer>
      </div>
    </div>
  );
};

export default App;
